services:
- type: web
  name: secure-oauth-server
  env: docker
  repo: https://github.com/dnilasor/oauth2-proxy
  envVars:
    - key: OAUTH2_PROXY_CLIENT_ID
      sync: false # placeholder for the Client ID to be added securely in the Render dashboard
    - key: OAUTH2_PROXY_CLIENT_SECRET
      sync: false # placeholder for the Client Secret to be added securely in the Render dashboard
    - key: OAUTH2_PROXY_PROVIDER
      value: google
